version: "3.9"
services:
  shareway_be_service:
    container_name: shareway-be
    build: .
    restart: always
    ports:
      - "35000:8080"
    depends_on:
      postgres_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      # rabbitmq:
      #   condition: service_healthy
    networks:
      - shareway-network

  postgres_db:
    image: postgres:17-alpine
    container_name: shareway-db
    restart: always
    environment:
      POSTGRES_USER: trilm
      POSTGRES_PASSWORD: Minhtricute69.
      POSTGRES_DB: shareway
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shareway-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trilm -d shareway"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: shareway-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shareway-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # rabbitmq:
  #   image: rabbitmq:4-management-alpine
  #   container_name: shareway-rabbitmq
  #   restart: always
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   networks:
  #     - shareway-network
  #   healthcheck:
  #     test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

volumes:
  postgres_data:
  redis_data:
  # rabbitmq_data:

networks:
  shareway-network:
    driver: bridge
