version: "3.9"
services:
  shareway_be_service:
    container_name: shareway-be
    build: .
    restart: always
    ports:
      - "35000:8080" # change port here
    depends_on:
      - postgres_db
      - redis
    networks:
      - shareway-network

  postgres_db:
    image: postgres:17-alpine
    container_name: shareway-db
    restart: always
    environment:
      POSTGRES_USER: trilm
      POSTGRES_PASSWORD: Minhtricute69.
      POSTGRES_DB: shareway
    ports:
      - "5433:5432" # Map to port 5433 on the host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shareway-network

  redis:
    image: redis:alpine
    container_name: shareway-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shareway-network

volumes:
  postgres_data:
  redis_data:

networks:
  shareway-network:
    driver: bridge
